--CRIAR A SEQUENCIA PARA A CHAVE INCREMENTAL DA TABELA DIMENSÃO CLIENTE
create sequence DIM_CLIENTE_ID_SEQ
increment by 1
minvalue 1
maxvalue 999999
start 1;

-- CRIAR A TABELA DIMENSÃO CLIENTE 
create table DIM_CLIENTE (
	SK_CLIENTE INTEGER primary key not null default NEXTVAL('DIM_CLIENTE_ID_SEQ'), -- CHAVE ARTIFICIAL AUTO-INCREMENTO
	NK_CLIENTE VARCHAR(100) not null,
	NM_CLIENTE VARCHAR(100) not null,
	NM_EMAIL VARCHAR(100) not null,
	DT_CARGA TIMESTAMP not null 
);


--CRIAR A SEQUENCIA PARA A CHAVE INCREMENTAL DA TABELA DIMENSÃO PRODUTO
create sequence DIM_PRODUTO_ID_SEQ
increment by 1
minvalue 1
maxvalue 999999
start 1;

-- CRIAR A TABELA DIMENSÃO PRODUTO 
create table DIM_PRODUTO (
	SK_PRODUTO INTEGER primary key not null default NEXTVAL('DIM_PRODUTO_ID_SEQ'), -- CHAVE ARTIFICIAL AUTO-INCREMENTO
	NK_PRODUTO VARCHAR(100),
	NM_PRODUTO VARCHAR(100),
	CAT_PRODUTO VARCHAR(100),
	VL_PRODUTO NUMERIC(12,4),
	STATUS_PRODUTO VARCHAR(50),
	DT_CARGA TIMESTAMP not NULL
);


-- CRIAR TABELA DIMENSÃO DATA OU TEMPO
create table DIM_DATA(
		SK_DATA INTEGER not null, -- 20160101
		"DATA" DATE not null,
		DESC_DATA_COMPLETA VARCHAR(60) not null, -- 01 JANEIRO DE 2017
		NR_ANO INTEGER not null, -- 2017
		NR_TRIMESTRE VARCHAR(20) not null, -- 1T
		NR_ANO_TRIMESTRE VARCHAR(20) not null, -- 2017/1T
		NR_MES INTEGER not null, -- 01
		NM_MES VARCHAR(20) not null, -- JANEIRO
		ANO_MES VARCHAR(20) not null, -- 2017/01
		NR_SEMANA INTEGER not null, -- 34
		ANO_SEMANA VARCHAR(20) not null, -- 2017/34
		NR_DIA INTEGER not null, -- 01
		NR_DIA_ANO INTEGER not null, -- 2017/31
		NM_DIA_SEMANA VARCHAR(20) not null, -- QUINTA-FEIRA
		FLAG_FINAL_SEMANA CHAR(3) not null, -- SIM/NÃO
		FLAG_FERIADO CHAR(3) not null, -- SIM/NÃO
		NM_FERIADO VARCHAR(60) not null, -- NATAL, ANO NOVO, PASCOA, CARNAVAL, ETC, ...
		DT_CARGA TIMESTAMP not null, -- 01/01/2017 23:59:00
		constraint SK_DATA_PK primary key (SK_DATA)
);


-- CRIAR TABELA FATO VENDA
create table FATO_VENDA(
	SK_DATA INTEGER not null,
	SK_CLIENTE INTEGER not null,
	SK_PRODUTO INTEGER not null,
	QTD_VENDA INTEGER not null,
	VL_VENDA_UNI NUMERIC(12,4) not null,
	VL_VENDA_TOTAL NUMERIC(12,4) not null,
	DT_CARGA TIMESTAMP not null,
	constraint FATO_VENDA_DIM_CLIENTE_FK foreign key (SK_CLIENTE) references DIM_CLIENTE(SK_CLIENTE),
	constraint FATO_VENDA_DIM_PRODUTO_FK foreign key (SK_PRODUTO) references DIM_PRODUTO(SK_PRODUTO),
	constraint FATO_VENDA_DIM_DATA_FK foreign key (SK_DATA) references DIM_DATA(SK_DATA)	
);