-- CRIANDO TABELA CLIENTE NA STAGE AREA
create table ST_CLIENTE(
	CD_CLIENTE INTEGER,
	NOME_CLIENTE VARCHAR(255),
	EMAIL_CLIENTE VARCHAR(255),
	DT_CARGA TIMESTAMP not NULL
);


-- CRIANDO TABELA PRODUTO NA STAGE AREA
create table ST_PRODUTO(
	COD_PRODUTO VARCHAR(255),
	NOME_PRODUTO VARCHAR(255),
	CAT_PRODUTO VARCHAR(255),
	PRECO_PRODUTO numeric(12,4),
	STATUS_PRODUTO VARCHAR(255),
	DT_CARGA TIMESTAMP not NULL
);

-- CRIANDO TABELA VENDA NA STAGE AREA
create table ST_VENDA(
	DT_VENDA DATE,
	COD_VENDA INTEGER,
	COD_PRODUTO VARCHAR(255),
	COD_CLIENTE VARCHAR(255),
	QTD_VENDA INTEGER,
	VL_VENDA NUMERIC(12,4),
	STATUS_VENDA VARCHAR(255),
	DT_CARGA TIMESTAMP not null
);

-- CRIANDO VIEW VENDAS NA STAGE AREA PARA OS DADOS SEREM INSERIDOS NA FATO VENDAS
 create view vw_st_venda as
	 select dt_venda, cod_cliente, cod_produto, qtd_venda, vl_venda, qtd_venda * vl_venda as vl_venda_total 
	 from st_venda ;
	

-- VALIDANDO VIEW VENDAS
select * from vw_st_venda;